{
 "title": "Monika Dashboard v1.0.1",
 "description": "Monika is an open source and free synthetic monitoring command line application. The name Monika stands for \"Monitoring Berkala\", which means \"periodic monitoring\" in the Indonesian language.\n\nGitHub: https://github.com/hyperjumptech/monika",
 "tags": [ "monika" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monika_probes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Running Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monika_probes_running_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Alerts Triggered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monika_alerts_triggered_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Notifications Triggered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monika_notifications_triggered_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "targets": [
    { "expr": "monika_probes_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alerts Triggered",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(id) (monika_alerts_triggered)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications Triggered",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (monika_notifications_triggered)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Running Probes by Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "monika_probes_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Probes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "monika_probes_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probes Status by Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "monika_probes_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probe Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "monika_probes_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Probes Response Size by Time (in bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monika_request_response_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probes Request Response Size (in bytes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "monika_request_response_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probes Avg. Response Time by Time (in milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(monika_request_response_time_seconds_sum[$__range]) / rate(monika_request_response_time_seconds_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probes Avg. Response Time (in milliseconds)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(monika_request_response_time_seconds_sum[$__range]) / rate(monika_request_response_time_seconds_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Notifications Triggered by Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "changes(monika_notifications_triggered[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications Triggered by Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "monika_notifications_triggered", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful Notifications Triggered by Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "changes(monika_notifications_triggered{status=\"success\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Notifications Triggered by Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "monika_notifications_triggered{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Notifications Triggered by Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "changes(monika_notifications_triggered{status=\"failed\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Notifications Triggered by Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "monika_notifications_triggered{status=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Alerts Triggered by Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "changes(monika_alerts_triggered[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Triggered by Probe",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "monika_alerts_triggered", "legendFormat": "__auto" }
   ]
  }
 ]
}